# OPENAI_API_KEY: "sk-91BTci1AhiJvn8cygZehrMNYuNuqCFgN3cBHzTBjoz3A310x"
# OPENAI_API_MODEL: "kimi-k2-turbo-preview"
# OPENAI_BASE_URL: "https://api.moonshot.cn/v1"
# global_proxy: ""
# # OPENAI_API_KEY: ""
OPENAI_API_KEY: "sk-IMblefS5KQ5ET8izUvenvX71tOXiIZDp3ICQ33mFcUtKV8lq"
OPENAI_API_MODEL: "deepseek-r1:32b-q8"
OPENAI_API_BASE: "http://10.10.63.35:8000/v1"
GLOBAL_PROXY: ""