# OPENAI_API_KEY: "sk-91BTci1AhiJvn8cygZehrMNYuNuqCFgN3cBHzTBjoz3A310x"
# OPENAI_API_MODEL: "kimi-k2-turbo-preview"
# OPENAI_BASE_URL: "https://api.moonshot.cn/v1"
# global_proxy: ""
# # OPENAI_API_KEY: ""
# OPENAI_API_KEY: "sk-IMblefS5KQ5ET8izUvenvX71tOXiIZDp3ICQ33mFcUtKV8lq"
# OPENAI_API_MODEL: "deepseek-r1:32b-q8"
# OPENAI_API_BASE: "http://10.10.63.35:8000/v1"
# GLOBAL_PROXY: ""
# shen
# OPENAI_API_KEY: "sk-25f781189f5a4a2cb98cebac77ae80d4"
# xiong
# OPENAI_API_KEY: "sk-77b0e287277c4daa87cf554027a3866f"
# jia
# OPENAI_API_KEY: "sk-5f80641e1c0e4229b878a515b8fa2562"
#zhu
OPENAI_API_KEY: "sk-1a9f44a66268417ea5118ee12cd459f2"
#lin
# OPENAI_API_KEY: "sk-5076dde0f8e24e43a8dc130a1945405c"
#lu cha
# OPENAI_API_KEY: "sk-c0a94a4eed2640eaaf2e0288109d8f7a"
#zongyue
# OPENAI_API_KEY: "sk-340c6de96b7e4d3aa62b7f4f1847b6b4"
#yuan cha
# OPENAI_API_KEY: "sk-20080d6a08ba423da7317dc237764dae"
#doubao
# OPENAI_API_KEY: "c3b9beae-7259-401a-91f2-493f73a1ce18"

OPENAI_API_MODEL: "deepseek-v3.1"
# OPENAI_API_MODEL: "deepseek-v3-1-250821"
OPENAI_API_BASE: "https://dashscope.aliyuncs.com/compatible-mode/v1"
# OPENAI_API_BASE: "https://ark.cn-beijing.volces.com/api/v3"
GLOBAL_PROXY: ""