# OPENAI_API_KEY: "sk-91BTci1AhiJvn8cygZehrMNYuNuqCFgN3cBHzTBjoz3A310x"
# OPENAI_API_MODEL: "kimi-k2-turbo-preview"
# OPENAI_BASE_URL: "https://api.moonshot.cn/v1"
# global_proxy: ""
# # OPENAI_API_KEY: ""
# OPENAI_API_KEY: "sk-IMblefS5KQ5ET8izUvenvX71tOXiIZDp3ICQ33mFcUtKV8lq"
# OPENAI_API_MODEL: "deepseek-r1:32b-q8"
# OPENAI_API_BASE: "http://10.10.63.35:8000/v1"
# GLOBAL_PROXY: ""

# OPENAI_API_KEY: "sk-25f781189f5a4a2cb98cebac77ae80d4"
OPENAI_API_KEY: "sk-77b0e287277c4daa87cf554027a3866f"
OPENAI_API_MODEL: "deepseek-v3.1"
OPENAI_API_BASE: "https://dashscope.aliyuncs.com/compatible-mode/v1"
GLOBAL_PROXY: ""